### PR TITLE
Memory footprint

### PR DESCRIPTION
**Pull request by the8472**
This avoids loading the `Messenger` module and thus the per-frame module loading which instantiates a lot of objects. Instead the same functionality is handled by a single sandbox that accesses all frames in a content process.

I have taken care to unload everything before nuking the sandbox, so no *"cannot access dead object"* exceptions should occur.

### CODE REVIEW

**Comment by Quicksaver** [comment]
I've wanted to optimize cross-process handling for a long time, so thank you for the initiative here!

- That first commit really should be in its own PR.

- Nits:
  - Always use leading tabs instead of spaces.
  - Newlines at EOF.
  - Close all statements with ```;``` e.g. first commit, ```callback(null)``` should be ```callback(null);```. There are more.
  - Any file loaded through ```Modules``` must avoid all global const/var/let declarations as much as possible, since those can't be deleted when unloading the module; that is why pretty much all of my code starts with ```this.someObject = {```.

> reduce footprint by passing |this| to JSM and then letting the script get GCed

- Wouldn't wrapping the current resource/modules/utils/content.js script into a constructor inside a JSM module (like your frameModule.jsm) produce roughly the same end result with far less code changes? (I know it would still have to construct the object each time, but its prototype being pretty much all of it would already be fully instantiated, hence the "roughly".)

- Have you measured the difference this causes per-tab? While it's true that new objects are created with each new tab, that's by design, so that the same code structure can be used in both chrome and content processes.

  - The biggest point of ```Messenger```, similarly to all other utils/helper modules, is to help me abstract from the implementation of cross-process communication (i.e. "tabgroups:" in every message), which your patch completely undoes.
  - Or in other words, all files that are not in the utils folder should have access to all tools inside those utils folders, or at least to those tools relevant to the scope they are being loaded in. It's true that your patch exceptionally optimizes that particular piece of TabView code in that it only loads and uses what it needs. But the same could probably be done throughout the whole add-on, and throughout all my other add-ons. I'd rather sacrifice a little performance (keyword being "little", as from my tests at the time, this hardly takes any toll at all) for the sake of ease of maintenance.
  - The biggest and most clear example is you merged api.jsm and TabView.jsm. They **must** be kept separate, API.jsm is used in all of my add-ons unmodified. It must stay that way, otherwise it will become maintenance hell.

**Comment by the8472** [comment]
> Any file loaded through Modules must avoid all global const/var/let declarations as much as possible, since those can't be deleted when unloading the module

I'll change it, but imo that makes it a bad module system.

>  Have you measured the difference this causes per-tab? 

Difficult to measure since GC cycles already cause the memory footprint to fluctuate a lot on my tab-heavy profile.
But what is easily measurable is the startup time.

2m24s on v1.0.1
1m30s patched

> That first commit really should be in its own PR.

Eh, byproduct of those changes, adjacent to the changes, building an XPI from multiple branches is a pain etc. etc. ;)

> Wouldn't wrapping the current resource/modules/utils/content.js script into a constructor inside a JSM module (like your frameModule.jsm) produce roughly the same end result with far less code changes? (I know it would still have to construct the object each time, but its prototype being pretty much all of it would already be fully instantiated, hence the "roughly".)

That thing loads subscripts, which have their own overhead AIUI. Not to mention that it does a lot of work for relatively little API surface in the end.

And the object instantiations themselves of course. The way I have written it the code is very very light on allocations. It always registers the same function instances as callbacks with the frames.

> The biggest point of Messenger, similarly to all other utils/helper modules, is to help me abstract from the implementation of cross-process communication (i.e. "tabgroups:" in every message), which your patch completely undoes.

The changes in [TabView.jsm](https://github.com/Quicksaver/Tab-Groups/pull/47/files#diff-3ce8a7b70876944afce0fd0c38431a68) are minimal though, considering the amount of abstraction i have shaved away.

>  But the same could probably be done throughout the whole add-on, and throughout all my other add-ons.

The issue with your module system is that instantiates everything over and over again instead of sharing instances. Which is tolerable if you do it per browser window, but it costs performance if you do it for every single tab.
I only applied the optimizations where it was most pressing.

> They must be kept separate, API.jsm is used in all of my add-ons unmodified. It must stay that way, otherwise it will become maintenance hell.

I guess it could be optimized separately by using a process script + document observer instead of working with frame scripts.

Keeping it as it is right now would pretty much negate all benefits because it depends on the whole module-loading-per-frame machinery.

**Comment by pauricthelodger** [comment]
Hey,

Just wondering how per browser window will work with Electrolysis?

**Comment by the8472** [comment]
Not really relevant to this PR, but in general it is unaffected by e10s because that particular part is chrome-only code.

The webextensions plan may be a different story since the goal there is to move addons to separate processes too.

**Comment by Quicksaver** [comment]
> 2m24s on v1.0.1
1m30s patched

Is that 2minutes? Holy hell I am no where near that kind of startup time, and I have a pretty slow system already on a profile with dozens of tabs too, and all five of my add-ons that load frame scripts in each tab in the same way... Something's wrong there, have you checked if that also happens when you disable all your other add-ons except for Tab Groups?

Even 1 minute is a lot no matter how many tabs you have... When you say tab-heavy profile, what are we talking about, high dozens, low hundreds, more? Are you loading all tabs on startup or are they loaded as you select them?

> I'll change it, but imo that makes it a bad module system.

There are many reasons that make it a bad module system, IMO that's the lesser of them. ;)

> The issue with your module system is that instantiates everything over and over again instead of sharing instances.

That is indeed one of the biggest issues with the current system, although Tab Groups isn't the best example because it is probably the only case that could live with a shared instance like you created in your patch. But most of the rest of my code requires keeping track of variables and functions scoped to a particular window/tab, which just can't happen with shared JSMs. Which is why I wrote it like this from the start.

And I meant to mention this before but forgot in the middle of everything. WebExtensions are the reason I haven't done any of this kind of optimizations yet. It's almost assured that the add-on will require major rewrites to... well pretty much everything, regardless of how many WEAPIs there will be and how they will work. It's hard to commit to major changes like these if in six months they force me to port the add-on to WEAPIs and thrash everything again to start over.

**Comment by the8472** [comment]
> Even 1 minute is a lot no matter how many tabs you have... When you say tab-heavy profile, what are we talking about, high dozens, low hundreds, more?

Around 1k

> Are you loading all tabs on startup or are they loaded as you select them?

They are lazy-loaded, but that makes no difference as far as frame scripts are concerned because lazy tabs are still about:blank windows which will be subject to any overhead caused by frame scripts.

**Comment by Quicksaver** [comment]
As a point of curiosity, how much of your approach would be nullified by each tab running in its own separate process? I'm guessing everything except the part of GC'ing the initial script, which would be next to nothing then. Do you know if I'm far off here?

Context, from https://developer.mozilla.org/Firefox/Multiprocess_Firefox/Message_Manager/Message_manager_overview
> In future versions of multiprocess Firefox different tabs may run in different processes, but for now, all content tabs share a single content process.

**Comment by the8472** [comment]
I'd say there would still be small savings simply by loading less code, but the overhead of creating a thousand processes absolutely dwarf any gains. Firefox would be unusable under such a scenario.

I have talked with the e10s devs about that and the plans aren't very precise yet. It might end up being a process-per domain or something similar. Some co-location in processes will happen either way because spawned tabs can access their parents via window.opener.

**Comment by the8472** [comment]
addressed your nits, moved the page API thing to a separate file.

**Comment by Quicksaver** [comment]
After merging locally, I had to refactor some of the code to make it fit the add-on backbone (bad077c0e8288150b9860046f1d18bf6dae4975b), so that the same approach can be used in my other add-ons, because as I mentioned your patch was too specific to Tab Groups.

The difference in performance from your patch is minimal in my testing, not noticeable at all for me. Could you try it out and see how it performs in your tab-heavy profile from before, to make sure I didn't significantly regress it?

**Comment by the8472** [comment]
Updated to 2506dcf and its footprint looks pretty good in comparison to 1.0.2.

Everything seems to be nicely contained in the sandbox. No more thousand-fold redundant `script-sources` entries in `about:memory`. So even if tab groups would still manage to leak memory somehow all it takes is an addon disable/enable cycle to nuke everything. :)

I think we could still be a bit smarter about the memory usage of each thumbnail, I'll file a separate issue about that.

**Comment by Quicksaver** [comment]
That is awesome to hear! Thank you for double-checking. :)

**Pull request merged**
