### PR TITLE
Remove trailing whitespace in all files

### PR DESCRIPTION
**Pull request by poke**
Per comment in #14, here would be a PR that removes all trailing whitespace in this project. That way you would have a “clean” way to get rid of it.

Note that the commit is too large for GitHub, so if you want to check it out, fetch it locally, or look at the [whitespace-ignoring diff](https://github.com/Quicksaver/Tab-Groups/commit/1444746f6164b817499ba75c8d2b36e8cf307e56?w=1) to see that nothing else changes ;)

### CODE REVIEW

**Comment by Quicksaver** [comment]
To answer your question in #14, it's not that it can't trim trailing whitespaces, but it doesn't do it automatically, and that function needs to be called on each file.

Anyway, I have gotten much better with my Regex since I've last checked this out, so I think I got a working macro for it now. Thanks for the motivation! BTW I don't think there would be much point in pulling your patch if I couldn't do it in my editor, otherwise trailing whitespaces would keep crawling back with each new patch (I auto-indent on new lines, hence the massive patch you generated). :)

**Comment by the8472** [comment]
You could set it as git commit hook so it does it for you automatically.

**Comment by Quicksaver** [comment]
True, I did look into it. Doing it in the editor directly just seems more easy. For instance, git doesn't seem to do anything "automatically" with hooks, it would abort the commit if it found whitespaces. Plus, it only works for new commits, not for existing code, so I'd still need to pull this patch and then do the same for all my other add-ons because I couldn't stand such a big difference in coding style between them. ;)

**Comment by the8472** [comment]
>  BTW I don't think there would be much point in pulling your patch if I couldn't do it in my editor

I think the intent is to keep future diffs smaller if they would otherwise apply auto-trim

**Comment by Quicksaver** [comment]
> I think the intent is to keep future diffs smaller if they would otherwise apply auto-trim

Exactly. I add lines with trailing whitespaces, you edit them and remove them, I add more, you remove them, etc. That's what I want to avoid, unless I also remove them like everyone else does (I should have done this from the start of course) there's no point.

**Pull request merged**
