### PR TITLE
update thumbnails during video playback

### PR DESCRIPTION
**Pull request by the8472**

### CODE REVIEW

**Comment by Quicksaver** [comment]
Yep there is. Ok let's try it. By the way, this time I'm applying the patch manually (it's small enough that it's easy and I already did it to try it locally), because of all the fake positive line changes it would create for the AMO reviewers like that.

Yeah I know, it's just a nit and maybe they wouldn't be bothered much. And I should have done that from the start but my editor doesn't trim spaces from lines automatically. :( Maybe it's me being nitpicky with my coding layout, but I prefer consistency over optimizations like that (which let's face it is not optimizing all that much, if at all). I hope you understand if I do the same for other smaller patches you may write in the future. :) (Larger patches I probably won't even bother with that and just pull it directly.)

**Comment by poke** [comment]
> but I prefer consistency over optimizations

Completely agree here, but you should still get rid of all the trailing white space eventually ;) Maybe make one commit where you fix that all? (If you want, I can assist with that)

What editor are you using that it keeps all that whitespace?

**Comment by the8472** [comment]
> because of all the fake positive line changes it would create for the AMO reviewers like that.

git diff can ignore whitespaces, so that shouldn't really be an issue.

Even github does it: https://github.com/the8472/Tab-Groups/commit/b9d76a0500a297283ea262998a686485abef2324?w=0

**Comment by Quicksaver** [comment]
I don't think AMO reviewers use git for diffs (or if they do, don't know if it uses that option automatically).

**Comment by the8472** [comment]
>  I hope you understand if I do the same for other smaller patches you may write in the future. 

It would be nicer if you would cherry-pick + amend in the future to preserve the author of the commit.

Or just ask the contributor to make the necessary changes himself if you don't like it for whatever codestyle reasons.

**Comment by Quicksaver** [comment]
Oh I'm sorry, I didn't know you could pick from pull requests, I thought they were an all-or-nothing kind of thing. I'll be sure to do that yeah. I did credit you on the release notes though.

**Comment by poke** [comment]
You can fetch pull requests individually from the command line using a special ref. For this one, you could have done `git fetch origin pull/14/head:local-branch-name` to create a new branch `local-branch-name` that contains the changes of this pull request. And then you can mess with it like usual and finally merge it into `master` to complete it.

**Pull request closed without merging**
