### PR TITLE
fix memory leak on chrome tabs

### PR DESCRIPTION
**Pull request by the8472**
FF automatically severs references to content windows, but not to chrome
windows. use weak refs instead so those can be GCed too.

### CODE REVIEW

**Comment by Quicksaver** [comment]
The ```onceListeners``` array holds references to each ```runOnce()``` method, not to the subject.

Where exactly is the leak, is it the subject node holding a reference to the runOnce method after the add-on's been disabled, or the method itself holding references to closed windows/tabs?

**Comment by the8472** [comment]
the latter.

**Comment by Quicksaver** [comment]
Changing ```runOnce``` to an object like ```{ weakSubject, handler }``` should work, where the handler itself would look for weakSubject rather than the subject directly. Do you agree?

**Comment by the8472** [comment]
I considered that, but my solution leaves fewer strong edges since it also makes the handler weakly reachable if the subject gets closed.

**Comment by Quicksaver** [comment]
Right, that's what I meant... So does this? (I'm not the biggest expert on GC, so I may be missing something obvious).
```Javascript
function removeOnceListener(oncer) {
	for(var i=0; i<onceListeners.length; i++) {
		if(!oncer) {
			onceListeners[i]();
			continue;
		}

		if(onceListeners[i] == oncer) {
			onceListeners.splice(i, 1);
			return;
		}
	}

	if(!oncer) {
		onceListeners = [];
	}
}

function listenOnce(aSubject, type, handler, capture) {
	if(UNLOADED || !aSubject || !aSubject.addEventListener) { return; }

	let runOnce = {
		weakSubject: Cu.getWeakReference(aSubject),
		handler: function(event) {
			let wSubject = this.weakSubject.get();
			try {
				if(wSubject) {
					wSubject.removeEventListener(type, this.handler, capture);
				}
			}
			catch(ex) { handleDeadObject(ex); } // Prevents some can't access dead object errors
			if(!UNLOADED && event !== undefined) {
				removeOnceListener(this);
				try {
					if(wSubject) {
						handler(event, wSubject);
					}
				}
				catch(ex) { Cu.reportError(ex); }
			}
		}
	};

	aSubject.addEventListener(type, runOnce.handler, capture);
	onceListeners.push(runOnce);
}
```

That way, aSubject is not directly held anywhere, and it should be GC'd regardless of the method still being in the array or not. If the event is fired, aSubject definitely exists and we're golden. If aSubject doesn't exist on shutdown, it's simply skipped and the array is destroyed in the end anyway.

(Optimally, there should be a heartbeat to check for the validity of all weakSubjects, so it self-cleans as necessary, but I'm not sure of how much benefit that would actually bring, seeing that a heartbeat like that always takes needs its own resources.)

**Comment by the8472** [comment]
> So does this?

No, your approach would not work for two reasons

a) aSubject would still be in the scope chain since all the inter functions close over listenOnce
b) you would still strongly hold onto `handler`, which in turn may have `aSubject` in its scope chain from its time of instantiation


Anyway, why not just take my solution, I already verified that it removes the leak. What's wrong with it?

**Comment by Quicksaver** [comment]
This: ;)
> The onceListeners array holds references to each runOnce() method, not to the subject.

removeOnceListener() won't work because you're storing weakSubjects and everything else expects it to have the actually runOnce() method.

**Comment by the8472** [comment]
Uhm. I [changed it](https://github.com/Quicksaver/Tab-Groups/pull/194/commits/bf80401e290da91c1389668530756a27f6b0f8d0#diff-b83c0bde60e252508b3088b391d3c14fR185) to handle the new array contents.

**Comment by the8472** [comment]
Oh wait, now I see what you mean, I forget to rename some variables. Sorry.

But that doesn't require a new approach, it just requires a few renames ;)

**Comment by the8472** [comment]
Better?

**Comment by Quicksaver** [comment]
It's still the same problem. ```unwrappable``` is a subject, a DOM node, it's not callable.

```listenOnce()``` stores a ```runOnce()``` method. This method is self-removing, meaning it's the method itself that handles its removal from the subject. This happens either when the event is fired, or on shutdown (by still calling the ```runOnce()``` method, but not the original event listener).

The ```runOnce``` method passes itself to ```removeOnceListener```, so that it is removed from the ```onceListeners``` array. This array is kept so that on shutdown (disabling the add-on), all uncalled listeners from events that were never fired are not held by each subject if they still exist.

It's nulling the leaks because that's the only case where it is actually working correctly. I'm sure that if you check, on shutdown methods from non-fired events are still held by the subjects.

**Comment by Quicksaver** [comment]
You're doing this basically:
```Javascript
let weak = Cu.getWeakReference(aSubject);
...
let unwrapped = weak.get();
if(unwrapped) {
  weak();
}
```

**Comment by Quicksaver** [comment]
And the comparison ```unwrapped == oncer``` will never be true, because oncer == runOnce != subject.

**Comment by the8472** [comment]
Well, that's embarrassing. Now the code should reflect my intent more closely... I hope.

**Comment by Quicksaver** [comment]
I think you made some mistake, I'm seeing the same thing as before.

**Comment by the8472** [comment]
It's weak-reffing the function now, not the subject: https://github.com/Quicksaver/Tab-Groups/pull/194/commits/0aa8e6547cf0fea3bc041d580c9ce9cd21871542#diff-b83c0bde60e252508b3088b391d3c14fR226

**Comment by Quicksaver** [comment]
Oh I'm so sorry, completely missed that.

Does it work? I have the impression the method itself should still exist regardless of if the tab (subject) still exists. Have you tested?

**Comment by Quicksaver** [comment]
(I'm sorry if that's a dumb question, I've never seen weak references for functions like that, only for DOM nodes.)

**Comment by the8472** [comment]
Dumb commits warrant dumb questions ;) Yes, the leak is still fixed with the updated version. It works because if the listener is still registered it's merely a cyclical reference between the listener and the window. But there's no path from the addon compartment to the window or the listener.

**Comment by Quicksaver** [comment]
Awesome! Thanks for the explanation. If I can just ask you to get rid of the extra new lines at 213, 227 and 228, I'll merge right away. :)

**Comment by the8472** [comment]
Done

**Comment by Quicksaver** [comment]
Fantastic! Thank you for working on this, and even finding it in the first place. :)

**Pull request merged**
